### ISSUE TITLE
CreativeCore and CMDCam crashed

### ISSUE THREAD

**Issue by HDGamer259** [CreativeMD/CMDCam#100]
i downloaded both creativecore and cmdcam for 1.12.2 and this occured when i launched minecraft:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CamPatchingLoader (CMDCam_v1.4.4_mc1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 7/13/24 10:44 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CMDCam (cmdcam)
Caused by: java.lang.NoSuchMethodError: com.creativemd.creativecore.common.packet.CreativeCorePacket.registerPacket(Ljava/lang/Class;Ljava/lang/String;)V
	at com.creativemd.cmdcam.CMDCam.Init(CMDCam.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 256383288 bytes (244 MB) / 536870912 bytes (512 MB) up to 14025752576 bytes (13376 MB)
	JVM Flags: 7 total; -Xmx13350M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version      | Source                             | Signature                                |
	|:----- |:-------------------------- |:------------ |:---------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft                  | 1.12.2       | minecraft.jar                      | None                                     |
	| LCHI  | mcp                        | 9.42         | minecraft.jar                      | None                                     |
	| LCHI  | FML                        | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                      | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | creativecoredummy          | 1.0.0        | minecraft.jar                      | None                                     |
	| LCHE  | cmdcam                     | 1.4.0        | CMDCam_v1.4.4_mc1.12.2.jar         | None                                     |
	| LCH   | creativecore               | 1.10.0       | CreativeCore_v1.10.71_mc1.12.2.jar | None                                     |
	| LCH   | tlauncher_custom_cape_skin | 1.4          | tlskincape_1.12.2-1.4.jar          | None                                     |

	Loaded coremods (and transformers): 
CamPatchingLoader (CMDCam_v1.4.4_mc1.12.2.jar)
  com.creativemd.cmdcam.transform.CamTransformer
CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
  
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 24.3.1.240216' Renderer: 'AMD Radeon RX 580 2048SP'

**Comment by CreativeMD** [comment]
Update CMDCam.
