### ISSUE TITLE
1.20.1 - Crash when player dies at same time as follow entity / while player dies when playing cam path 

### ISSUE THREAD

**Issue by xLasttDev** [CreativeMD/CMDCam#102]
[crash-2024-08-24_23.02.50-client.txt](https://github.com/user-attachments/files/16738845/crash-2024-08-24_23.02.50-client.txt)

> Time: 2024-08-24 23:02:50
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "x" because "vec" is null
	at team.creative.creativecore.common.util.math.vec.Vec3d.set(Vec3d.java:62) ~[CreativeCore_FORGE_v2.11.37_mc1.20.1.jar%23314!/:2.11.37] {re:classloading}
	at team.creative.creativecore.common.util.math.vec.Vec3d.set(Vec3d.java:11) ~[CreativeCore_FORGE_v2.11.37_mc1.20.1.jar%23314!/:2.11.37] {re:classloading}
	at team.creative.creativecore.common.util.math.vec.VecNd.<init>(VecNd.java:17) ~[CreativeCore_FORGE_v2.11.37_mc1.20.1.jar%23314!/:2.11.37] {re:classloading}
	at team.creative.creativecore.common.util.math.vec.Vec3d.<init>(Vec3d.java:33) ~[CreativeCore_FORGE_v2.11.37_mc1.20.1.jar%23314!/:2.11.37] {re:classloading}
	at team.creative.cmdcam.common.scene.run.CamRunStage.calculatePoint(CamRunStage.java:100) ~[CMDCam_FORGE_v2.1.1_mc1.20.1.jar%23307!/:2.1.1] {re:classloading}
	at team.creative.cmdcam.common.scene.run.CamRun.renderTick(CamRun.java:134) ~[CMDCam_FORGE_v2.1.1_mc1.20.1.jar%23307!/:2.1.1] {re:classloading,pl:runtimedistcleaner:A}
	at team.creative.cmdcam.common.scene.CamScene.renderTick(CamScene.java:199) ~[CMDCam_FORGE_v2.1.1_mc1.20.1.jar%23307!/:2.1.1] {re:mixin,re:classloading}
	at team.creative.cmdcam.client.CMDCamClient.renderTickPath(CMDCamClient.java:226) ~[CMDCam_FORGE_v2.1.1_mc1.20.1.jar%23307!/:2.1.1] {re:mixin,re:classloading}
	at team.creative.cmdcam.client.CamEventHandlerClient.onRenderTick(CamEventHandlerClient.java:153) ~[CMDCam_FORGE_v2.1.1_mc1.20.1.jar%23307!/:2.1.1] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at team.creative.cmdcam.client.__CamEventHandlerClient_onRenderTick_RenderTickEvent.invoke(.dynamic) ~[CMDCam_FORGE_v2.1.1_mc1.20.1.jar%23307!/:2.1.1] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onRenderTickStart(ForgeEventFactory.java:905) ~[forge-1.20.1-47.3.7-universal.jar%23377!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.potential_spawns_alloc.ForgeEventFactoryMixin,pl:mixin:APP:lithium.mixins.json:collections.mob_spawning.ForgeEventFactoryMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1144) ~[client-1.20.1-20230612.114412-srg.jar%23372!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23372!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.3.7.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
