### ISSUE TITLE
Erro when loading addon

### ISSUE THREAD

**Issue by thunderlight411** [CreativeMD/CMDCam#25]
Crash while startup MC Client

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 3/28/20 11:15 AM
Description: Unexpected error

java.lang.NoClassDefFoundError: team/creative/creativecore/common/network/CreativePacket
	at team.creative.cmdcam.client.CamEventHandlerClient.setupMouseHandlerBefore(CamEventHandlerClient.java:231) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_78473_a(GameRenderer.java) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:cmdcam:changeMouseOver,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1338) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:905) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.30.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$395/1144897090.call(Unknown Source) [forge-1.15.2-31.1.30.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}
Caused by: java.lang.ClassNotFoundException: team.creative.creativecore.common.network.CreativePacket
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.0.0-milestone.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2637373776 bytes (2515 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.30.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.30.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.30.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.30.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.30.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.30
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.30-client.jar Minecraft {minecraft@1.15.2 NONE}
		forge-1.15.2-31.1.30-universal.jar Forge {forge@31.1.30 NONE}
		Xaeros_Minimap_20.5.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.5.0 NONE}
		CMDCam_v1.5.5_mc1.15.2.jar CMDCam {cmdcam@1.5.0 NONE}
		LightOverlay-4.2.jar Light Overlay Forge {lightoverlay-forge@4.2 NONE}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 NONE}
	Launched Version: 1.15.2-forge-31.1.30
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon RX 5700 GL version 4.6.13587 Compatibility Profile Context 20.2.1 26.20.15019.1003, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/1.15.2-r1.zip
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor

**Comment by CreativeMD** [comment]
You are missing CreativeCore. Normally forge should show you that, but for some reason it just crashes. Hope this will change at some point.
