### ISSUE TITLE
unexpected error with cam follow pos x y z

### ISSUE THREAD

**Issue by deaconblues2020** [CreativeMD/CMDCam#89]
this happened in single player - here is the stack trace: 

[28Dec2023 13:05:53.555] [Render thread/ERROR] [net.minecraftforge.client.ClientCommandHandler/]: Error executing client command "cam follow pos 100 100 100"
java.lang.UnsupportedOperationException: Attempted to get server level in client command
	at net.minecraftforge.client.ClientCommandSourceStack.m_81372_(ClientCommandSourceStack.java:151) ~[forge-1.20.1-47.2.0-universal.jar%23169!/:?]
	at net.minecraft.commands.arguments.coordinates.BlockPosArgument.m_118242_(BlockPosArgument.java:33) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at team.creative.cmdcam.common.command.builder.TargetArgumentBuilder.lambda$build$9(TargetArgumentBuilder.java:87) ~[CMDCam_FORGE_v2.1.0_mc1.20.1%20(3).jar%23161!/:2.1.0]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar%23113!/:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.1.8.jar%23113!/:?]
	at net.minecraftforge.client.ClientCommandHandler.runCommand(ClientCommandHandler.java:161) ~[forge-1.20.1-47.2.0-universal.jar%23169!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_246623_(ClientPacketListener.java:2418) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.gui.screens.ChatScreen.m_241797_(ChatScreen.java:223) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.optifine.gui.GuiChatOF.m_241797_(GuiChatOF.java:38) ~[OptiFine_1.20.1_HD_U_I6.jar%23170!/:?]
	at net.minecraft.client.gui.screens.ChatScreen.m_7933_(ChatScreen.java:101) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.KeyboardHandler.lambda$onKeyEvent$5(KeyboardHandler.java:565) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:531) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.KeyboardHandler.lambda$setupCallbacks$8(KeyboardHandler.java:723) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.KeyboardHandler.lambda$setupCallbacks$9(KeyboardHandler.java:722) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23153!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:210) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:221) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:376) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23164!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?
...

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
