### ISSUE TITLE
Minecraft crash when change mode to outside

### ISSUE THREAD

**Issue by blueshadowlaser2023** [CreativeMD/CMDCam#91]
Time: 2/21/24 7:28 AM

XRay version: 58

Description: Unexpected error

java.lang.ClassCastException: net.minecraft.entity.monster.EntityZombie cannot be cast to net.minecraft.entity.player.EntityPlayer

at io.github.blaezdev.rwbym.EntityUpdatesHandler.onEvent(EntityUpdatesHandler.java:197)

......

See the below you could fount it have a error at rwbym.EntityUpdatesHandler.onEvent(EntityUpdatesHandler.java:197)

......

-- Head --

Thread: Client thread

Stacktrace:

at io.github.blaezdev.rwbym.EntityUpdatesHandler.onEvent(EntityUpdatesHandler.java:197)

at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1615_EntityUpdatesHandler_onEvent_FogColors.invoke(.dynamic)

Disable rwbym4.6.7, then it's ok. No crash. But if you do not chang the mode, there is no crash.

event:
CMDCam_v1.4.12_mc1.12.2.jar
CreativeCore_v1.10.71_mc1.12.2.jar

**Comment by CreativeMD** [comment]
Seems like an issue with the `rwbym` mod. Furthermore it's for 1.12.2 and I do not support this version anymore. Sorry.
